# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:8000/auth/login?code=10&scope=uno+@diego/dos&state=con%20espacio")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("xuser1")
    self.driver.find_element(By.NAME, "password").send_keys("secreto")
    assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(8) > label").text == "uno"
    assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) > label").text == "@diego/dos"
    self.driver.find_element(By.NAME, "scope_extra").click()
    self.driver.find_element(By.NAME, "scope_extra").send_keys("otromas")
    self.driver.find_element(By.NAME, "redirect_uri").click()
    self.driver.find_element(By.NAME, "redirect_uri").send_keys("http://mauriciocap.com")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(19)").click()
    self.driver.implicitly_wait(30)
    assert self.driver.find_element(By.LINK_TEXT, "Agilidad Empresarial").text == "Agilidad Empresarial"
  
