# Generated by Selenium IDE

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#SEE: https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html
from secrets import token_urlsafe
import requests
import os

TEST_HOST= os.environ.get('TEST_HOST', 'http://localhost:8000')

class TestFormjs():
	def setup_method(self, method):
		self.driver = webdriver.Firefox()
		self.vars = {}
	
	def teardown_method(self, method):
		self.driver.quit()
	
	def test_formjs(self):
		mark= token_urlsafe(10)
		self.driver.get(f"{TEST_HOST}/static/form_contacto_js.html")
		self.driver.find_element(By.ID, "name").send_keys(f"xtest {mark}")
		self.driver.find_element(By.ID, "email").send_keys(f"xtest_delete_me@{mark}.com")
		self.driver.find_element(By.ID, "subject").send_keys(f"xtest subject <bla> ; sql {mark}")
		self.driver.find_element(By.NAME, "message").send_keys(f"xtest body\\n<pre>\\n;\\nselect\\n																			 space {mark}")
		self.driver.find_element(By.CSS_SELECTOR, "button").click()
		WebDriverWait(self.driver, 30,
			EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".sent-message"),
				"Your message has been sent. Thank you!"
			)
		)
	
		res= requests.get(f"{TEST_HOST}/data/?fmt=json&entity=any",
	    headers={ "accept": "application/json" },
		)
		data= res.json()
		match= [d for d in data if mark in d['more_data']]
		print("MATCH", match)
		assert len(match)==1		


